/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Puls2.H
**     Project   : galaxy2012_V0_1
**     Processor : 56F8013VFAE
**     Component : PulseAccumulator
**     Version   : Component 01.183, Driver 02.03, CPU db: 2.87.097
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2012/6/26, 8:56
**     Abstract  :
**          Pulse accumulator counts the number of active edges at the input of its
**          channel.
**     Settings  :
**             Pulse accumulator       : TMR2_PACNT
**
**
**         Used input pin              :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       19            |  GPIOB4_T0_CLKO
**             ----------------------------------------------------
**
**         Mode                        : Count
**
**         Initialization:
**              Pulse accumulator      : Disabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TMR2_CNTR [61477]
**              Hold                   : TMR2_HOLD [61476]
**              Run                    : TMR2_CTRL [61478]
**              Prescaler              : TMR2_CTRL [61478]
**
**         User handling procedure     : not specified
**
**     Contents  :
**         Enable           - byte Puls2_Enable(void);
**         Disable          - byte Puls2_Disable(void);
**         ResetCounter     - void Puls2_ResetCounter(void);
**         GetCounterValue  - void Puls2_GetCounterValue(word *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __Puls2
#define __Puls2

/* MODULE Puls2. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#ifndef __BWUserType_Puls2_TCounterValue
#define __BWUserType_Puls2_TCounterValue
  typedef word Puls2_TCounterValue;    /* Counter value, width depend on on selected peripheal. */
#endif


byte Puls2_Enable(void);
/*
** ===================================================================
**     Method      :  Puls2_Enable (component PulseAccumulator)
**
**     Description :
**         Enables the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte Puls2_Disable(void);
/*
** ===================================================================
**     Method      :  Puls2_Disable (component PulseAccumulator)
**
**     Description :
**         Disables the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

void Puls2_ResetCounter(void);
/*
** ===================================================================
**     Method      :  Puls2_ResetCounter (component PulseAccumulator)
**
**     Description :
**         This method resets the pulse accumulator counter (sets to
**         zero).
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Puls2_GetCounterValue(Puls2_TCounterValue *Value);
/*
** ===================================================================
**     Method      :  Puls2_GetCounterValue (component PulseAccumulator)
**
**     Description :
**         This method returns the content of the pulse accumulator
**         counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - Pointer to returned value. [Note:]
**                           Parameter type depends on the width of the
**                           selected counter (may be 8, 16, 32 or 64
**                           bits long). See the method prototype in the
**                           generated module.
**     Returns     : Nothing
** ===================================================================
*/

void Puls2_Init(void);
/*
** ===================================================================
**     Method      :  Puls2_Init (component PulseAccumulator)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END Puls2. */

#endif /* ifndef __Puls2 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
